# Generated by Django 3.2.9 on 2022-07-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('név', models.CharField(max_length=30)),
                ('leiras', models.CharField(max_length=300)),
                ('public', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projektek',
            },
        ),
    ]
