# Generated by Django 3.2.9 on 2022-07-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_projekt_projektszam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projekt',
            name='projektszam',
            field=models.IntegerField(),
        ),
    ]
