# Generated by Django 3.2.9 on 2022-07-23 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_alter_projekt_leiras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projekt',
            name='projektszam',
        ),
    ]
