# Generated by Django 3.2.9 on 2022-07-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0008_alter_projekt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projekt',
            name='id',
            field=models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
