# Generated by Django 3.2.9 on 2022-07-23 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0009_alter_projekt_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kepek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('felirat', models.CharField(max_length=30)),
                ('url', models.URLField()),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.projekt')),
            ],
            options={
                'verbose_name': 'Kép',
                'verbose_name_plural': 'Képek',
            },
        ),
    ]
