# Generated by Django 3.2.9 on 2022-07-23 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0012_auto_20220723_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kepek',
            name='felirat',
        ),
        migrations.AddField(
            model_name='kapcsolo',
            name='key',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='APP.projekt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kapcsolo',
            name='id',
            field=models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kepek',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.kapcsolo'),
        ),
    ]
