# Generated by Django 3.2.9 on 2022-07-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0013_auto_20220723_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kapcsolo',
            options={'verbose_name': 'Kapcsolo', 'verbose_name_plural': 'Kapcsolo'},
        ),
    ]
