# Generated by Django 3.2.9 on 2022-07-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0015_alter_kapcsolo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fooldal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategoria', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=100)),
                ('sorszam', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='projekt',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='projekt',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
